### ISSUE TITLE
Resolving path with serverless

### ISSUE THREAD

**Issue by andrewkislev** [Vadorequest/serverless-with-next5-boilerplate#4]
Hey @Vadorequest. Did you find how to serve data from `build` folder? I'm trying to integrate serverless to existing Nodejs project which perfectly runs from `build/server.default`, but if I user serverless with 

```yml
functions:
  server:
    handler: /build/server.default
    events:
      - http:
          method: GET
          path: /
      - http:
          method: GET
          path: /build/{proxy+}
```

it can't find any files in build/static/*.js
