### ISSUE TITLE
Error: Cannot find module '<module>'

### ISSUE THREAD

**Issue by remy** [Vadorequest/serverless-with-next5-boilerplate#9]
Hi there,

I've been following along this repo over the last few days and making progress in deploying to AWS (so thanks!).

Specifically though I've been hitting a problem where a 3rd party dep in my `/pages/index.js` doesn't seem to be found. I don't know webpack well enough to understand the issue, but it doesn't happen locally, and I wonder if it's somehow being excluded from the build that's uploaded?

In the `webpack.config.js`, I've included this:

```
externals: [nodeExternals({ whitelist: ['nprogress'] })],
```

(Where nprogress is the module that isn't found) - but this makes no difference to the deploy - which fails saying it can't be found.

Any ideas or suggestions? 

Thanks in advance.

**Comment by Vadorequest** [comment]
@remy I'm glad you find it useful!

Indeed, webpack is complicated... You probably just missed your dependency in serverless.yml `webpackIncludeModules.forceInclude`

`serverless-webpack` use some kind of "smart" algorithm and add dependencies used in the project, but it failed me a lot of time to be honest, here is my current stuff to give you an idea:

```yml
custom:
  serverless-offline:
    port: 3000 # We run our SLS/Express endpoints there (Next app will run on 3001)
  webpackIncludeModules:
    # Enable auto-packing of external modules
    # See https://serverless-stack.com/chapters/add-support-for-es6-es7-javascript.html
    forceInclude:
      - classnames
      - deepmerge
      - http-proxy
      - htmlescape
      - next-redux-wrapper
      - prop-types
      - react-hotjar
      - react-redux
      - react-select
      - react-style-proptype
      - reactstrap
      - recompose
      - redux-devtools-extension # Shouldn't be necessary, but it is because of the way it's imported
      - redux-thunk
      - styled-jsx
```

Hope it helps!
